name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          wget -c "https://dl-cdn.alpinelinux.org/alpine/v3.12/main/$arch/apk-tools-static-2.10.6-r0.apk" -O apk-tools-static.apk
          tar -zxf apk-tools-static.apk
          sudo install sbin/apk.static /bin/apk
          sudo chmod +x /bin/apk
          sudo apk --arch x86_64 -X "http://dl-cdn.alpinelinux.org/alpine/latest-stable/main/" -U --allow-untrusted --root chroot --initdb add alpine-base bash
          sudo mount --bind /dev chroot/dev
          sudo mount --bind /sys chroot/sys
          sudo mount --bind /proc chroot/proc
          sudo mount --bind /run chroot/run
          sudo git clone $(git remote get-url origin) chroot/build
          sudo mkdir chroot/output/
          sudo chroot chroot bash -ex /build/build.sh

      - uses: actions/upload-artifact@v2
        with:
            name: output
            path: chroot/output/*


